apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "citrix-master-project", "product_id": "citrix-k8s-ingress-controller", "partner_name": "Citrix"}'
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    type: CITRIX
    version: '1.13.15'
    description: |-
      People-centric solutions for a better way to work
    maintainers:
    - name: Citrix
      url: https://cloud.google.com/solutions/#click-to-deploy
    links:
    - description: 'CITRIX: Getting Started'
      url: https://www.citrix.com/
    notes: |-
      # Configuring CITRIX Controller
      Configuring CITRIX Controller
  info:
  - name: Application Namespace
    value: {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
  - group: ''
    kind: ConfigMap
  - group: apps
    kind: Deployment
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: networking.k8s.io
    kind: IngressClass
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: monitoring.coreos.com
    kind: ServiceMonitor
